makers_form/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'pages/index'

  resources :forms

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
end

makers_form/app/models/form.rb
class Form < ActiveRecord::Base
	# validates :firstname, presence: true, length: {maximum: 50}
	# validates :lastname, presence: true, length: {maximum: 50}
	# validates_format_of :email, presence: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	# validates :phone, presence: true, length: {maximum: 11}
	# validates :reason, presence: true, length: {minimum: 80,maximum: 250}
	# validates :experience, presence: true, length: {minimum: 80,maximum: 250}
end

makers_form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

makers_form/app/controllers/forms_controller.rb
class FormsController < ApplicationController
	def index
		@forms = Form.all
	end

	def show
    	@form = Form.find(params[:id])
  	end

	def new
		 
	end

	def create
  		@form = Form.new(form_params)
 
  		@form.save
  		redirect_to @form
	end

	private
		def form_params
			params.require(:form).permit(:firstname, :lastname, :email, :phone, :reason, :experience)
			# params.require(:forms).permit(:firstname, :lastname, :email, :phone, :reason, :experience)
		end
end

makers_form/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

makers_form/app/helpers/application_helper.rb
module ApplicationHelper
end

makers_form/app/helpers/forms_helper.rb
module FormsHelper
end

makers_form/app/helpers/pages_helper.rb
module PagesHelper
end

makers_form/app/views/forms/extra.html.erb
<body>
	<header>
		<div id="logo">
			
		</div>
		<div class="apply">
			<h1>
				APPLY TO MAKERS ACADEMY
			</h1>
			<!-- <h4>
				Apply now and take your first step to kickstarting your career as a Junior Developer.
			</h4> -->
		</div>
		<div class="apply">
			Apply now and take your first step to kickstarting your career as a Junior Developer.
		</div>
	</header>

	<!-- <h1 class="container">Application form</h1>-->
	<div class="container">
		<%= form_for :form, url: forms_path do |f| %>

	  <p class="form-group">
	    <%= f.label :firstname %><br>
	    <%= f.text_field :firstname, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :lastname %><br>
	    <%= f.text_field :lastname, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :email %><br>
	    <%= f.email_field :email, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :phone %><br>
	    <%= f.text_field :phone, class: 'form-control' %>
	  </p>

	  <h2 class="header1">LET'S TALK A LITTLE BIT MORE ABOUT YOU</h2>
	 
	 <h3>Why do you want to attend Makers Academy?</h3>
	 <h4>Build the next Facebook? Change the world? Quit a boring job and start an exciting career? Make lots of money as a software developer? Just because you like coding?</h4>
	 <h5>(Please keep your response between 80 - 250 words!)</h5>
	  <p class="form-group">
	    <%= f.text_area :reason, class: 'form-control', rows: '12' %>
	  </p>

	   <h3>How have you learnt to code so far?</h3>
	 <h4>If you can't code, it won't count against you: all you need is passion and the ability to unlearn the word "quit."</h4>
	 <h5>(Please keep your response between 80 - 250 words!)</h5>
	  <p class="form-group">
	  	<%= f.text_area :experience, class: 'form-control', rows: '12' %>
	  </p>

	  <h3>How did you hear about us?</h4>
	  <h4>Purely for marketing reasons. If you heard about us through multiple channels, choose the one that influenced your decision the most.</h5>
	  <p class="form-group">
	  	<%= f.label "Select an option..." %>
	  	<%= f.select(:option_type, options_for_select(['Google', 'Twiiter', 'Quora'])) %>
	  </p>
	 
	  <p class="text-center">
	    <%= f.submit "Apply", class: 'btn btn-default'%>
	  </p>
	<% end %>
	</div>
	

</body>


<%= form_for :form, url: forms_path do |f| %>
  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </p>
 
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

makers_form/app/views/forms/index.html.erb
<h1>Listing forms</h1>
 
<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Phone number</th>
    <th>Reason</th>
    <th>Experience</th>
  </tr>
 
  <% @forms.each do |form| %>
    <tr>
      <td><%= form.firstname %></td>
      <td><%= form.lastname %></td>
      <td><%= form.email %></td>
      <td><%= form.phone %></td>
      <td><%= form.reason %></td>
      <td><%= form.experience %></td>
    </tr>
  <% end %>
</table>

makers_form/app/views/forms/new.html.erb
<body>
<body>
	<header>
		<div id="logo">
			
		</div>
		<div class="apply">
			<h1>
				APPLY TO MAKERS ACADEMY
			</h1>
			<!-- <h4>
				Apply now and take your first step to kickstarting your career as a Junior Developer.
			</h4> -->
		</div>
		<div class="apply">
			Apply now and take your first step to kickstarting your career as a Junior Developer.
		</div>
	</header>

	<!-- <h1 class="container">Application form</h1>-->
	<div class="container">
		<%= form_for :form, url: forms_path do |f| %>

	  <p class="form-group">
	    <%= f.label :firstname %><br>
	    <%= f.text_field :firstname, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :lastname %><br>
	    <%= f.text_field :lastname, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :email %><br>
	    <%= f.email_field :email, class: 'form-control' %>
	  </p>

	  <p class="form-group">
	    <%= f.label :phone %><br>
	    <%= f.text_field :phone, class: 'form-control' %>
	  </p>

	  <h2 class="header1">LET'S TALK A LITTLE BIT MORE ABOUT YOU</h2>
	 
	 <h3>Why do you want to attend Makers Academy?</h3>
	 <h4>Build the next Facebook? Change the world? Quit a boring job and start an exciting career? Make lots of money as a software developer? Just because you like coding?</h4>
	 <h5>(Please keep your response between 80 - 250 words!)</h5>
	  <p class="form-group">
	    <%= f.text_area :reason, class: 'form-control', rows: '12' %>
	  </p>

	   <h3>How have you learnt to code so far?</h3>
	 <h4>If you can't code, it won't count against you: all you need is passion and the ability to unlearn the word "quit."</h4>
	 <h5>(Please keep your response between 80 - 250 words!)</h5>
	  <p class="form-group">
	  	<%= f.text_area :experience, class: 'form-control', rows: '12' %>
	  </p>

	  <h3>How did you hear about us?</h4>
	  <h4>Purely for marketing reasons. If you heard about us through multiple channels, choose the one that influenced your decision the most.</h5>
	  <p class="form-group">
	  	<%= f.label "Select an option..." %>
	  	<%= f.select(:option_type, options_for_select(['Google', 'Twiiter', 'Quora'])) %>
	  </p>
	 
	  <p class="text-center">
	    <%= f.submit "Apply", class: 'btn btn-default'%>
	  </p>
	<% end %>
	</div>
	

</body>

makers_form/app/views/forms/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @form.firstname %>
</p>
 
<p>
  <strong>Lastname:</strong>
  <%= @form.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @form.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @form.phone %>
</p>

<p>
  <strong>Reason for applying:</strong>
  <%= @form.reason %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @form.experience %>
</p>

makers_form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakersForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

makers_form/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>